<div class="col-md-6 offset-md-3">
    <form>
        <div class="form-group">
            <label for="login">Login</label>
            <input type="text" class="form-control" id="login" name="login" placeholder="Nom de compte">
        </div>
        <div class="form-group">
            <label for="password">Mot de passe</label>
            <input type="password" class="form-control" id="password" placeholder="Mot de passe">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-info">Se connecter</button>
        </div>
    </form>
</div>